### ISSUE TITLE
Implement a means of marking model objects as "ReportAttachable" and automatically insert them into the report in json format POST CONSTRUCT

### ISSUE THREAD

**Issue by symonk** [symonk/sylenium-framework#21]
Users can create a number of objects, e.g -> PuppyOrder is a model object.  We should provide a means for users to mark such classes as models and they should be automatically written to the report.

perhaps a class level annotation of @Model? we can attach to the report using the following:

`Allure.addAttachment("Order.json", "application/json", new GsonBuilder().setPrettyPrinting().create().toJson(this));`

**Comment by nikhilbansal97** [comment]
Hi @symonk Can you provide some more detail or maybe an example?

**Comment by symonk** [comment]
Hi @nikhilbansal97 we can attach data/model objects to the report in json format using:

`Allure.addAttachment("Order.json", "application/json", new GsonBuilder().setPrettyPrinting().create().toJson(this));` for example.

We need a way of marking classes as models which should then be automatically attached to the report upon post construct.

An annotation / AOP is maybe a better option here?

**Comment by symonk** [comment]
implemented @modelable / Attachable interface/annotation and a means of serializing such objects into the report as attachments
