### ISSUE TITLE
Create annotation for non-frontend tests

### ISSUE THREAD

**Issue by symonk** [symonk/sylenium-framework#28]
hook into the annotation at runtime and if it exists, don't do the unnecessary selenium/selenide before/after test functionality.

Problem: Even on non gui tests, @after hooks are running causing problems.

**Comment by Jitsusama** [comment]
I’m willing to take a look at this. Just to make sure I handle it right, what logic can I reliably apply to differentiate between front-end and non-front-end tests in this code base?

**Comment by symonk** [comment]
the more I think of this it starts to make less sense, the entire gui-tests module is strictly for gui only tests, api-tests or others would live in their own module so I don't think its worthwhile doing this after all.  but thank you @Jitsusama

**Comment by Jitsusama** [comment]
You're most welcome. I was seeing the same thing, but I wasn't sure if there mightn't be some cross project contamination with GUI tests.
