### ISSUE TITLE
Start creating a basic contributors.md

### ISSUE THREAD

**Issue by symonk** [symonk/sylenium-framework#37]
Implement a very basic contributors md to start building upon

**Comment by manaswinidas** [comment]
I'm interested

**Comment by manaswinidas** [comment]
I think it has been already implemented.

**Comment by symonk** [comment]
the file is empty right now @manaswinidas even some basic improvements/content would be a good start

**Comment by manaswinidas** [comment]
As in details of the contributors?

**Comment by symonk** [comment]
basic information of how to start contributing to the project is all :)

**Comment by symonk** [comment]
e.g forking etc

**Comment by tanaytoshniwal** [comment]
I would like to work on this @symonk

**Comment by symonk** [comment]
thanks @tanaytoshniwal, I will await your PR
