### ISSUE TITLE
combine .github and .images into a sole folder (.resources)

### ISSUE THREAD

**Issue by symonk** [symonk/sylenium-framework#40]
create a .resources and move .github / .image content into folders inside of it.

**note:** please update all image links in the README.md to reflect the change(s)

**Comment by sebastiaanspeck** [comment]
Hello, I would like to assign this issue to me

**Comment by symonk** [comment]
thanks @sebastiaanspeck I will await your PR

**Comment by sebastiaanspeck** [comment]
Is it correct that only the report-dashboard.png and the performance-test.jpg are used in the README?

If you give me the use of the report-example-cases.png and the report-graph-data.png, I will change those links also.

**Comment by symonk** [comment]
so far I believe only those 2 files yep.  the other 2 I don't really care about now :) you can move them into the directory but we dont need to update their references anywhere right now
