### ISSUE TITLE
Investigate logs being written 3 times...

### ISSUE THREAD

**Issue by symonk** [symonk/sylenium-framework#41]
https://travis-ci.org/symonk/sylenium-framework/builds/436003038?utm_source=github_status&utm_medium=notification

`07:41:38 TestNG-test=Regression Pack-3 INFO WebEventListener Looking for element by: By.id: collar
 07:41:38 TestNG-test=Regression Pack-3 INFO WebEventListener Looking for element by: By.id: collar
 07:41:38 TestNG-test=Regression Pack-3 INFO WebEventListener Looking for element by: By.id: collar`

Why are the logs outputting exactly the same content every second? looks like a bug but it could be a parallel test coincedence

WebEventListener is a good place to start looking

**Comment by Jitsusama** [comment]
I’m willing to take a look at this.

**Comment by symonk** [comment]
thanks @Jitsusama look forward to seeing your PR

**Comment by Jitsusama** [comment]
_gui-tests/src/test/java/io.github.symonk/testsuites/Regression.xml_ is configured to run the tests in package _io.github.symonk.testcases.PuppyAdoptionTests_. This test class has a total of 3 test cases defined. It appears that these tests may be running in parallel, which could account for things. It's rather unfortunate that the logs do not denote the associated thread.

I'm going to dig a bit deeper to verify my assumptions. I haven't played with TestNG before, but I'm sure I'll figure things out.

**Comment by Jitsusama** [comment]
And never mind, I see that the tests are broken up by *Packs*, and the triplicated logs reference the same *Pack*. Back to the drawing board.

**Comment by Jitsusama** [comment]
Ok, I think I found it. I'm going to spend a bit more time validating, but I hope to have a PR put together soon.
