### ISSUE TITLE
Modify the Modelable default interface implementation of model();

### ISSUE THREAD

**Issue by symonk** [symonk/sylenium-framework#57]
During checks for reading the @Attachable annotation name value e.g `PuppyOrder.json` we should account for when .json is not included in the annotation.

- Parse the annotation value from Attachable
- if it does not end in ".json" amend it onto the string before Allure.addAttach(...) is called.

**Comment by symonk** [comment]
this will give our users the ability to use `@Attachable(name = "simple")` rather than forcing `@Attachable(name="simple.json")`

**Comment by sebastiaanspeck** [comment]
I am willing to take this. Can you give a bit more context where I can find the code that needs this changes?

**Comment by symonk** [comment]
@sebastiaanspeck https://github.com/symonk/sylenium-framework/blob/master/gui-tests/src/test/java/io.github.symonk/common/annotations/Modelable.java

**Comment by sebastiaanspeck** [comment]
Like this?:
```
if (!annoVal.endsWith('.json')) {
   annoVal = annoVal + '.json';
}
```

**Comment by symonk** [comment]
@sebastiaanspeck see my PR comment pretty much this but just in another place.

`if(!annoVal.endsWith(".json") annoVal = annoVal + ".json";`

**Comment by sebastiaanspeck** [comment]
This issue can be closed

**Comment by sebastiaanspeck** [comment]
This issue can be closed
