### ISSUE TITLE
Update references to old name selenide-framework and change to sylenium

### ISSUE THREAD

**Issue by symonk** [symonk/sylenium-framework#60]
Project used to be known as selenide-framework, this is confusing for contributors etc.  it should be re-referenced as sylenium.  This should just be a multiple pom.xml value override from selenium-framework to sylenium

**note:** selenide is a library itself and we should not modify anything to do with this code.

**Comment by sebastiaanspeck** [comment]
Issue can be closed

#58

**Comment by sebastiaanspeck** [comment]
Will you fix it? I got some time to do it

**Comment by symonk** [comment]
Hi @sebastiaanspeck this is slightly different, its in reference to things like this existing in pom.xml files:

`  <groupId>io.github.symonk</groupId>
    <artifactId>selenide-framework</artifactId>
    <packaging>pom</packaging>
    <version>1.0-SNAPSHOT</version>
    <modules>
        <module>api-tests</module>
        <module>gui-tests</module>
        <module>performance-tests</module>
    </modules>`

the only reference to selenide we should have is the library itself, we should rename all selenide-framework to "sylenium" instead

**Comment by sebastiaanspeck** [comment]
I can do it if you want. This has to be changed in all pom.xml-files?

**Comment by symonk** [comment]
Yep all module pom files, root and any of the sub modules.  "selenide-framework" should not exist at all in this project right now, all references should be instead "sylenium"

**Comment by symonk** [comment]
submodule being /api-tests && /gui-tests && /performance-tests && the main root pom.xml

**Comment by sebastiaanspeck** [comment]
See #62
